"""Small, exact quantum-error-correction research models.

The APIs in this package simulate error distributions and decoders. They do
not implement arbitrary circuits or a fault-tolerant quantum computer.
"""

from .three_qubit import (
    ERROR_PATTERNS,
    CandidateDiagnostic,
    CorrelatedNoiseDiagnostics,
    CorrelatedXXXNoise,
    DecodeDiagnostics,
    DecodeResult,
    ErrorPattern,
    ExactLogicalDiagnostics,
    LogicalClass,
    LogicalErrorType,
    Syndrome,
    decode_syndrome,
    exact_logical_diagnostics,
    exact_logical_error_rate,
    logical_failure,
    majority_vote_recovery,
    residual_after_recovery,
    syndrome_for_error,
)
from .tensor_network import (
    CalculationKind,
    CorrelatedNoiseTensorNetwork,
    LogicalPosteriorTensorResult,
    SyndromeConditioning,
    TensorNetworkContraction,
    build_correlated_noise_tensor_network,
    contract_correlated_noise_tensor_network,
    tensor_error_pattern_probabilities,
    tensor_fixed_syndrome_probability,
    tensor_logical_posteriors,
    tensor_logical_syndrome_probabilities,
    tensor_syndrome_probabilities,
)
from .monte_carlo import (
    MonteCarloResult,
    MonteCarloSamples,
    estimate_logical_error_rate,
    run_monte_carlo,
)
from .visualization import (
    EXPORT_COLUMNS,
    ErrorWeightSeries,
    LogicalPosteriorPlotResult,
    SyndromeDistributionResult,
    export_results_csv,
    plot_backend_performance,
    plot_error_weight_distribution,
    plot_logical_posteriors,
    plot_monte_carlo_convergence,
    plot_physical_vs_logical_rate,
    plot_syndrome_distribution,
    results_to_dataframe,
    results_to_rows,
)

__all__ = [
    "ERROR_PATTERNS",
    "CandidateDiagnostic",
    "CalculationKind",
    "CorrelatedNoiseDiagnostics",
    "CorrelatedNoiseTensorNetwork",
    "CorrelatedXXXNoise",
    "DecodeDiagnostics",
    "DecodeResult",
    "ErrorPattern",
    "ErrorWeightSeries",
    "EXPORT_COLUMNS",
    "ExactLogicalDiagnostics",
    "LogicalClass",
    "LogicalErrorType",
    "LogicalPosteriorTensorResult",
    "LogicalPosteriorPlotResult",
    "MonteCarloResult",
    "MonteCarloSamples",
    "Syndrome",
    "SyndromeConditioning",
    "SyndromeDistributionResult",
    "TensorNetworkContraction",
    "build_correlated_noise_tensor_network",
    "contract_correlated_noise_tensor_network",
    "decode_syndrome",
    "exact_logical_diagnostics",
    "exact_logical_error_rate",
    "estimate_logical_error_rate",
    "export_results_csv",
    "logical_failure",
    "majority_vote_recovery",
    "plot_backend_performance",
    "plot_error_weight_distribution",
    "plot_logical_posteriors",
    "plot_monte_carlo_convergence",
    "plot_physical_vs_logical_rate",
    "plot_syndrome_distribution",
    "residual_after_recovery",
    "run_monte_carlo",
    "results_to_dataframe",
    "results_to_rows",
    "syndrome_for_error",
    "tensor_error_pattern_probabilities",
    "tensor_fixed_syndrome_probability",
    "tensor_logical_posteriors",
    "tensor_logical_syndrome_probabilities",
    "tensor_syndrome_probabilities",
]
